#!/bin/bash
recipient='example@example.com'
subject="examplesubject"
preword="Hello dear $recipient,"
mailcontent="just some sample text here"
signature="sincerely yours, $USER from $HOSTNAME"
placeholder1=""
placeholder2=""
placeholder3=""
echo $preword$placeholder1$mailcontent$placeholder2$placeholder3$signature | neomutt -s $subject $recipient
